---
title: "R para Ingenier칤as"
author: "La Academia"
subtitle: "Tema 00 - Pr치ctica"
output:
  html_document:
    df_print: paged
---

# Introducci칩n a RStudio y R Markdown

## Ejercicio 1

Crea un bloque de texto donde hayan al menos dos p치rrafos donde comentas sobre tus expectativas respecto al curso. Resalta con cursiva, negrita o ambas, las partes que consideres m치s importantes.

Luego a침ade una lista no numerada en la cual enlistes las posibles aplicaciones que t칰 podr치s realizar durante el curso y al finalizarlo.

## Soluci칩n

Ingresa tu respuesta aqu칤 游놓

------------------------------------------------------------------------

## Ejercicio 2

De seguro en alguna ocasi칩n has tenido que ir a hacer compras a una papeler칤a, ya sea por inicio de clases o por algo similar. 쮿as hecho una lista de las compras que debes hacer? Crea una lista numerada con todas las compras que normalmente haces. Adem치s, clasifica tus compras por grupos a침adiendo subniveles a tu lista.

**Por ejemplo:**

1.  Cuadernos
    1.  Universitario a cuadros 100 hojas
    2.  Universitario a cuadros 200 hojas
    3.  Peque침o sin l칤neas 50 hojas
2.  Esferos
    1.  Azul, rojo y negro
    2.  Borrable de varios colores
3.  Pinturas
    1.  Temperas de 10 colores

Al final a침ade una imagen de la papeler칤a donde sueles hacer tus compras.

**Observaci칩n:** La imagen la puedes descargar de internet o cargar a trav칠s de su enlace.

## Soluci칩n

Ingresa tu respuesta aqu칤 游놓

------------------------------------------------------------------------

## Ejercicio 3

Ahora vamos a repasar los hiperv칤nculos. Por lo tanto, vas a crear los siguientes hiperv칤nculos:

-   Un hiperv칤nculo que te lleve al inicio de este archivo de c칩digo. *Pista:* Utiliza el t칤tulo de este archivo como referencia.
-   Un hiperv칤nculo que te lleve al primer ejercicio.
-   Un hiperv칤nculo que te lleve al 칰ltimo ejercicio.
-   Un hiperv칤nculo que te lleve la p치gina de inicio este curso en Udemy: **R para Ingenier칤as**.
-   Consulta en Wikipedia sobre R y crea un hiperv칤nculo que te lleve a la p치gina web consultada.

## Soluci칩n

Ingresa tu respuesta aqu칤 游놓

------------------------------------------------------------------------

## Ejercicio 4

Consulta en internet sobre LaTeX (una gu칤a de inicio r치pido o un tutorial de introducci칩n es suficiente) y escribe las siguientes expresiones matem치ticas:

-   F칩rmula para determinar el volumen de un cilindro.
-   F칩rmula para obtener la hipotenusa de un tri치ngulo rect치ngulo is칩sceles.
-   F칩rmula para calcular el volumen de una esfera.
-   F칩rmula para determinar las ra칤ces de un polinomio de segundo grado (conocida como f칩rmula general de segundo grado).

Y, si te animas a este desaf칤o, tambi칠n escribe las siguientes expresiones matem치ticas:

-   Definici칩n matem치tica de la derivada (en una variable).

-   Definici칩n matem치tica de la integral (en una variable).

-   Una ecuaci칩n diferencial en derivadas parciales (la que t칰 quieras).

## Soluci칩n

Ingresa tu respuesta aqu칤 游놓

------------------------------------------------------------------------

## Ejercicio 5

En la universidad tenemos un horario de las materias que tomamos en cada semestre. A continuaci칩n genera una tabla con tu horario del semestre actual.

-   Si todav칤a no entras a la universidad, entonces crea una tabla con tu horario del colegio.

-   Si ya terminaste la universidad, entonces crea una tabla con el horario del 칰ltimo semestre que cursaste.

Luego, a침ade una imagen de la universidad donde estudias, quieres estudiar o estudiaste.

## Soluci칩n

Ingresa tu respuesta aqu칤 游놓

------------------------------------------------------------------------
